services:
  postgres-db:
    image: postgres:14-alpine
    container_name: petrefugio_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NSdandandograu@123
      POSTGRES_DB: petrefugio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: